# 기출 1

In [1]:
a,b = 10, 11.4
print(a, 100, 200, b, sep='x', end='???')

10x100x200x11.4???

* <틀림, 다시보기>

In [3]:
a = 'hello world'
print(a[1:5],a[:5],a[-1])

#ello hello d 

# 띄어쓰기 주의

ello hello d


In [4]:
a = 'hello world'
print(a.upper().replace('H','xyz'))

#HELLO WORLD
#xyzELLO WORLD

xyzELLO WORLD


In [5]:
temp = 25.5
prob = 80.0
print('오늘 기온 {}도, 비올 확률 {}%'.format(temp, prob))

오늘 기온 25.5도, 비올 확률 80.0%


* <틀림, 다시보기>

In [6]:
a = 'hello world'
b = a.split('w')
print(type(b), b)

# list, hellowworld 

# <class 'list'> ['hello', 'orld']

<class 'list'> ['hello ', 'orld']


* <틀림, 다시보기>

In [7]:
a = 'ABC'
b = list(a)
print(b)

# [A,B,C]

# 작은 따옴표 주의

['A', 'B', 'C']


In [8]:
a = [1,2,3,4,5,6,7,8,9,10]
print(a[1:9:2])

# [2, 4, 6, 8]

[2, 4, 6, 8]


* <틀림, 다시보기>

In [10]:
a = [1,2,3]
b = [4,5,6]
a.append(b)
print(a)
a.extend(b)
print(a)

# [[1,2,3],[4,5,6]]
# [1,2,3,4,5,6]

#[1,2,3,[4,5,6],4,5,6]

[1, 2, 3, [4, 5, 6]]
[1, 2, 3, [4, 5, 6], 4, 5, 6]


In [12]:
a = {1:'A', 2:'B', 3:3, 0:'C'}
c = 'B' in a
print(a[0],c)

# C False

C False


In [13]:
a = {1:'A', 2:'B', 3:3, 0:'C'}
b = list(a.keys())
c = list(a.values())
print(b,c)

# [1,2,3,0] ['A','B',3,'C']

[1, 2, 3, 0] ['A', 'B', 3, 'C']


In [14]:
a = [1,10,20,100]
b = 0
for x in a:
    b += x
print(b)

# 131

131


In [15]:
if 6>5:
    print('6이 5보다 크다')
else:
    print('test')
    print('end')

# 6이 5보다 크다 

6이 5보다 크다


In [16]:
a = {1:'A', 2:'B', 3:3, 0:'C'}
for x in a:
    print(x)

# 1
# 2
# 3
# 0

1
2
3
0


In [17]:
a = {1:'A', 2:'B', 3:3, 0:'C'}
for x,y in a.items():
    print(x, y)
    
# 1 A
# 2 B
# 3 3
# 0 C

1 A
2 B
3 3
0 C


In [19]:
a = [10,20,30,40]
for x,y in enumerate(a):
    print(x)
    
# 0
# 1
# 2
# 3

0
1
2
3


In [21]:
for i in range(1, 10):
    for j in range(1,10):
        print(i,'x',j,'=',i*j)

1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81


In [22]:
def add(x,y,z=5):
    return x+y+z
a = add(1,2)
b = add(1,2,3)
print(a,b)

# 8 6

8 6


In [23]:
def test(x,y,z=5):
    print(x,y,z)
    return
test(z=10,x=4,y=3)

# 4 3 10

4 3 10


* <틀림, 다시보기>

In [25]:
def fun(x,y):
    return x+y, x*y
a= fun(2,3)
print(a)

# [5, 6]

# 리스트 x, 튜플 o

(5, 6)


* <틀림, 다시보기>

In [27]:
def test(*args):
    print(type(args))
    for x in args:
        print(x)
test(1,2,3)

# <class list>
# 1
# 2
# 3

# list x, tuple o

<class 'tuple'>
1
2
3


In [28]:
class Person:
    def __init__(self, name, age=10):
        self.name = name
        self.age = age
        self.hobby = 'singing'
p1 = Person('Bob', 30)
print(p1.name, p1.age)


Bob 30


In [31]:
class Studuent(Person):
    def __init__(self,name,age=10):
        self.name = name
        self.age = age
        self.hobby = 'singing'

In [32]:
import numpy as np
arr = np.array([[1,2],[1,2],[1,2]])
print(arr.shape)

# (3,2)

(3, 2)


* <틀림, 다시보기>

In [34]:
print(arr.reshape(2,-1))

# [[1,2,1],[2,1,2]]

# print 된건 콤마(,) 안쓰고 띄어쓰기

[[1 2 1]
 [2 1 2]]


* <틀림, 다시보기>

In [37]:
arr = np.array([[1,2],[1,2],[1,2]])
arr = np.expand_dims(arr, 0)
print(arr.shape)

# (0,3,2)

# 0 이 아니고 1

(1, 3, 2)


# 기출 2

In [39]:
a = "hello"
b = 'hello "world"'
print(a,b,a[-1],a[-2],a.upper(),sep=',')

# hello,hello "world",o,l,HELLO

hello,hello "world",o,l,HELLO


In [41]:
a.replace('h','hhh').upper()

# 'HHHELLO'

'HHHELLO'

In [43]:
c = 1, 2, 3
d = list(c)
print(c, d)

# (1,2,3) [1,2,3]

(1, 2, 3) [1, 2, 3]


* <틀림, 다시보기>

In [45]:
a = [1,2,3,4,5]
print(a[:], a[:2], a[1:], a[1:2])

# [1,2,3,4,5],[1,2,3,4,5],?

#[1,2,3,4,5] [1,2] [2,3,4,5] [2]

[1, 2, 3, 4, 5] [1, 2] [2, 3, 4, 5] [2]


In [46]:
a = [1,2,3,4,5]
a.insert(1,10)
print(a)

# [1,10,3,4,5]

[1, 10, 2, 3, 4, 5]


* <헷갈림, 다시보기>

In [48]:
a = [1,2,3,4,5]
a.remove(2)
print(a)

# [1,3,4,5]

[1, 3, 4, 5]


In [50]:
a = [1,2,3,4,5]
b = 3
c = b in a
print(c)

# True

True


In [51]:
a = [0,2,8,3,5,9,-1]
a.sort()
print(a)

# [-1,0,2,3,5,8,9]

[-1, 0, 2, 3, 5, 8, 9]


* <헷갈림, 다시보기>

In [52]:
a = {1:2, 3:4, 5:6, 7:8}
print(type(a), a[1], a.keys(), a.values())

# ()가 아니라 []

<class 'dict'> 2 dict_keys([1, 3, 5, 7]) dict_values([2, 4, 6, 8])


* <틀림, 다시보기>

In [54]:
a = {1:2, 3:4, 5:6, 7:8}
c = 2 in a
print(c, a.get(3))

# False ? 

# False 3 

False 4


In [56]:
a,b,c = 10, 20, 30
if(a==10 and b==20) or c==100:
    print('{} is true'.format('this'))
else:
    print('{} is false'.format('this'))
    
# this is true

this is true


In [57]:
a = [1, 10, 20, 100]
i = 0
while i < len(a)-1:
    print(a[i])
    i+=1

# 1
# 10
# 20

1
10
20


In [58]:
a = [1,10,20,100]
for x in a:
    print(x)
    
# 1
# 10
# 20
# 100

1
10
20
100


In [59]:
a = {1:2, 3:4, 5:6, 7:8}
for x in a:
    print(x)
    
# 1
# 3
# 5
# 7

1
3
5
7


In [60]:
a = {1:2, 3:4, 5:6, 7:8}
for x in a.values():
    print(x)
    
# 2
# 4
# 6
# 8

2
4
6
8


In [61]:
for x, y in a.items():
    print(x,y)
    
# 1 2
# 3 4
# 5 6
# 7 8

1 2
3 4
5 6
7 8


In [62]:
a = [1,3,2,2]
for x, y in enumerate(a):
    if y>=1:
        print(x,y)
        
# 0 1
# 1 3
# 2 2
# 3 2

0 1
1 3
2 2
3 2


In [63]:
b = list(range(10,15))
print(b)

# [10, 11, 12, 13, 14]

[10, 11, 12, 13, 14]


In [64]:
def fun(x,y,z=10):
    n = x+y-z
    m = x-y+z
    return n,m
print(fun(10,20), fun(10,20,30))

# (20, 0) (0, 20)

(20, 0) (0, 20)


In [66]:
num1, num2 = 10, 20
def add(num1, num2):
    print(num1, num2)
    return num1 + num2
add(30,40)
print(num1, num2)

# 30 40
# 10 20

30 40
10 20


In [67]:
def test(*args):
    print(type(args))
    for x in args:
        print(x)
test(10,20,30)

# <class 'tuple'>
# 10
# 20
# 30

<class 'tuple'>
10
20
30


In [68]:
f = lambda x,y : x+y
print(f(10,20))

# 30

30


* <틀림, 다시보기>

In [70]:
def str_len(s):
    return len(s)
strings = ['abcd', 'ab', 'abc', 'a']
strings.sort(key=str_len)
print(strings)

# a ab abc abcd

# ['a', 'ab', 'abc', 'abcd']

['a', 'ab', 'abc', 'abcd']


* <헷갈림, 다시보기>

In [71]:
a = [13,4,2,8,9]
b = list(map(lambda n:n%2==0, a))
print(b)

# [False,True,True,True,False]

[False, True, True, True, False]


In [72]:
import numpy as np

In [73]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([[1,2],[2,3],[3,4]])
print(arr1.shape, arr1[1,0],arr2.shape, arr2[2,1])

# (3,1) 2 (3,2) 4

(3, 1) 2 (3, 2) 4


* <틀림, 다시보기>

In [75]:
arr = np.arange(4,10)
print(arr)
print(arr.reshape(2,3))
print(arr.reshape(3,-1))

# [4 5 6 7 8 9]

# [[4 5 6]
#  [7 8 9]]

#[[4 5]
# [6 7]
# [8 9]]

[4 5 6 7 8 9]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [76]:
data = np.random.randint(3,size=6).reshape(2,3)
data

array([[2, 0, 2],
       [2, 2, 2]])

* <틀림, 다시보기>

In [78]:
data[data<=1] = 0.0
data

# array[0.0,0,0.0]

array([[2, 0, 2],
       [2, 2, 2]])

In [79]:
arr = np.array([[1,2],[2,3],[3,4]]).reshape(-1)
arr.shape

# (6,)

(6,)

* <틀림, 다시보기>

In [80]:
arr =np.array([[1,2],[2,3],[3,4]])
arr1 = np.expand_dims(arr,0)
arr2 = np.expand_dims(arr,1)
arr3 = np.expand_dims(arr,-1)
print(arr1)
print(arr1.shape)
print(arr2)
print(arr2.shape)
print(arr3)
print(arr3.shape)
# [[[1 2][2 3][3 4]]]
# (1,3,2)
# [[[[1 2][2 3][3 4]]]]
# (1,1,3,2)
# ?
# (1,1,3,2,1)

[[[1 2]
  [2 3]
  [3 4]]]
(1, 3, 2)
[[[1 2]]

 [[2 3]]

 [[3 4]]]
(3, 1, 2)
[[[1]
  [2]]

 [[2]
  [3]]

 [[3]
  [4]]]
(3, 2, 1)


In [81]:
class Person:
    def __init__(self,name, age):
        self.name = name
        self.age = age
        self.hobby = 'singing'